<!-- Generated by xAI Grok (model: gpt-5.4) during provisioning. Edit freely. -->
<script setup lang="ts">
const config = useRuntimeConfig()
const appName = config.public.appName || 'my-boat'
</script>

<template>
  <div class="min-h-screen flex flex-col">
    <header class="bg-primary-700 text-white py-4">
      <UContainer class="flex justify-between items-center">
        <div class="text-xl font-bold">{{ appName }}</div>
        <nav class="flex space-x-4">
          <NuxtLink to="/" class="hover:underline">Home</NuxtLink>
          <NuxtLink to="/about" class="hover:underline">About</NuxtLink>
          <NuxtLink to="/contact" class="hover:underline">Contact</NuxtLink>
        </nav>
      </UContainer>
    </header>
    <main class="flex-grow">
      <slot />
    </main>
    <footer class="bg-neutral-800 text-white py-4 text-center">
      <p>&copy; {{ new Date().getFullYear() }} {{ appName }}. All rights reserved.</p>
    </footer>
  </div>
</template>