<!-- Generated by xAI Grok (model: gpt-5.4) during provisioning. Edit freely. -->
<script setup lang="ts">
const config = useRuntimeConfig()
const appName = config.public.appName || 'my-boat'
const description = 'For serving up information about your boat for yourself and others. Soon to supersede the current https://mybo.at'

useSeo({
  title: `${appName} - Your Boat Information Hub`,
  description,
  ogImage: {
    title: appName,
    description
  }
})

useWebPageSchema({
  name: `${appName} - Your Boat Information Hub`,
  description
})

const features = [
  {
    icon: 'i-lucide-ship',
    title: 'Boat Details at Your Fingertips',
    description: 'Easily access and update information about your boat anytime, anywhere.'
  },
  {
    icon: 'i-lucide-share-2',
    title: 'Share with Others',
    description: 'Collaborate and share boat info with friends, family, or crew members.'
  },
  {
    icon: 'i-lucide-anchor',
    title: 'Secure and Reliable',
    description: 'Keep your boat data safe with enterprise-grade security.'
  }
]
</script>

<template>
  <UContainer class="min-h-screen flex flex-col">
    <section class="py-20 sm:py-32 text-center bg-gradient-to-br from-primary-50 to-primary-100">
      <h1 class="text-4xl sm:text-6xl font-bold text-primary-700 mb-4">{{ appName }}</h1>
      <p class="text-xl text-neutral-600 max-w-2xl mx-auto mb-8">Your ultimate hub for managing and sharing boat information. Superseding the current platform with modern features.</p>
      <UButton color="primary" size="xl" label="Get Started" to="/signup" />
    </section>

    <section class="py-16 sm:py-24">
      <h2 class="text-3xl font-semibold text-center text-neutral-800 mb-12">Why Choose my-boat?</h2>
      <div class="grid grid-cols-1 sm:grid-cols-3 gap-8">
        <UCard
          v-for="feature in features"
          :key="feature.title"
          :icon="feature.icon"
          :title="feature.title"
          :description="feature.description"
          class="shadow-lg"
        />
      </div>
    </section>

    <section class="py-16 sm:py-24 bg-neutral-50 text-center">
      <h2 class="text-3xl font-semibold text-neutral-800 mb-4">Ready to Set Sail?</h2>
      <p class="text-lg text-neutral-600 mb-8">Join us and revolutionize how you manage your boat information.</p>
      <UButton color="primary" size="lg" label="Sign Up Now" to="/signup" />
    </section>
  </UContainer>
</template>